#!/usr/bin/env bash

set -euo pipefail

original_arguments=("$@")
fixture_contract=''
fixture_mode='review'
session_name=''
session_id=''
model=''
reasoning_effort=''
context_tier=''
transcript_path=''
workdir=''

while (($# > 0)); do
    case "$1" in
        --fixture-contract)
            fixture_contract="${2-}"
            shift 2
            ;;
        --fixture-mode)
            fixture_mode="${2-}"
            shift 2
            ;;
        --workdir)
            workdir="${2-}"
            shift 2
            ;;
        --session-name)
            session_name="${2-}"
            shift 2
            ;;
        --session-id)
            session_id="${2-}"
            shift 2
            ;;
        --model)
            model="${2-}"
            shift 2
            ;;
        --reasoning-effort)
            reasoning_effort="${2-}"
            shift 2
            ;;
        --context)
            context_tier="${2-}"
            shift 2
            ;;
        --transcript)
            transcript_path="${2-}"
            shift 2
            ;;
        *)
            printf 'Unexpected no-op fixture argument: %s\n' "$1" >&2
            exit 64
            ;;
    esac
done

[[ -n "${session_name}" && -n "${session_id}" ]]
[[ "${model}" == 'noop-fixture-model' ]]
[[ "${reasoning_effort}" == 'max' ]]
[[ "${context_tier}" == 'long_context' ]]
[[ -n "${transcript_path}" ]]
[[ -n "${NOOP_RUNTIME_HOME:-}" ]]
[[ -f "${NOOP_RUNTIME_HOME}/fixture-runtime.json" ]]
[[ "$(stat -c '%a' "${NOOP_RUNTIME_HOME}")" == 700 ]]
[[ "$(stat -c '%a' "${NOOP_RUNTIME_HOME}/fixture-runtime.json")" == 600 ]]

capture_root="${NOOP_CAPTURE_ROOT:-}"
if [[ "${fixture_mode}" == report-repair && -n "${capture_root}" ]]; then
    capture_root="${capture_root%/}/report-repair"
fi

capture_fixture_state() {
    [[ -n "${capture_root}" ]] || return 0
    mkdir -p -- "${capture_root}"
    printf '%s\0' "${original_arguments[@]}" \
        > "${capture_root}/argv"
    env | LC_ALL=C sort > "${capture_root}/environment.txt"
    pwd > "${capture_root}/cwd.txt"
    printf '%s\n' "${NOOP_RUNTIME_HOME}" \
        > "${capture_root}/runtime-home.txt"
    find "${NOOP_RUNTIME_HOME}" \
        -printf '%P\t%m\t%y\n' |
        LC_ALL=C sort > "${capture_root}/runtime-inventory.txt"
    printf '%s\n' 'started' > "${capture_root}/started"
}

if [[ "${fixture_mode}" == report-repair ]]; then
    [[ "${fixture_contract}" == 4 ]]
    [[ -d "${workdir}" && ! -L "${workdir}" ]]
    cd -- "${workdir}"
    grep -Fq \
        '"Phase":"report-repair"' \
        "${NOOP_RUNTIME_HOME}/fixture-runtime.json"
    [[ -z "$(find . -mindepth 1 -print -quit)" ]]

    repair_prompt="$(cat)"
    repair_descriptor="$(
        printf '%s\n' "${repair_prompt}" |
            awk '
                $0 == "EXPECTED CONFIDENCE EDIT" {
                    marker_count++
                    if (getline descriptor <= 0) {
                        exit 65
                    }
                }
                END {
                    if (marker_count != 1 ||
                        descriptor !~ /^\{"ProtocolVersion":1,"Section":/ ||
                        descriptor !~ /"Field":"Confidence:"/ ||
                        descriptor !~ /"Occurrence":/ ||
                        descriptor !~ /"OriginalValueSha256":/ ||
                        descriptor !~ /"ConservativeLevel":/) {
                        exit 65
                    }
                    print descriptor
                }
            '
    )"

    case "${NOOP_REPAIR_RESPONSE_MODE:-stdout}" in
        stdout|transcript)
            cat > "${transcript_path}" <<EOF
# Development-only no-op harness report-repair transcript

### User

Return only the trusted expected confidence edit.

### Info

Development-only fixture transport; no tool response is authoritative.

### Copilot

${repair_descriptor}

---

<sub>Generated by [GitHub Copilot CLI](https://github.com/features/copilot/cli)</sub>
EOF
            ;;
        missing)
            cat > "${transcript_path}" <<'EOF'
# Development-only no-op harness report-repair transcript

### Copilot

No repair descriptor was returned.

---

<sub>Generated by [GitHub Copilot CLI](https://github.com/features/copilot/cli)</sub>
EOF
            ;;
        user-only)
            cat > "${transcript_path}" <<EOF
# Development-only no-op harness report-repair transcript

### User

${repair_descriptor}
EOF
            ;;
        system-only)
            cat > "${transcript_path}" <<EOF
# Development-only no-op harness report-repair transcript

### System

${repair_descriptor}
EOF
            ;;
        view-only)
            cat > "${transcript_path}" <<EOF
# Development-only no-op harness report-repair transcript

### \`view\`

${repair_descriptor}
EOF
            ;;
        view-failed)
            cat > "${transcript_path}" <<EOF
# Development-only no-op harness report-repair transcript

### \`view\` — Failed

${repair_descriptor}
EOF
            ;;
        task-completed)
            cat > "${transcript_path}" <<EOF
# Development-only no-op harness report-repair transcript

### task (Completed)

${repair_descriptor}
EOF
            ;;
        info-only)
            cat > "${transcript_path}" <<EOF
# Development-only no-op harness report-repair transcript

### Info

${repair_descriptor}
EOF
            ;;
        *)
            exit 66
            ;;
    esac
    capture_fixture_state
    if [[ "${NOOP_REPAIR_RESPONSE_MODE:-stdout}" == stdout ]]; then
        printf '%s\n' "${repair_descriptor}"
    else
        printf '%s\n' \
            'NOOP FIXTURE: repair reply is not present as pure standard output.'
    fi
    exit 0
fi

[[ "${fixture_mode}" == review ]]
[[ "${fixture_contract}" == 2 ]]
grep -Fq '"Phase":"review"' "${NOOP_RUNTIME_HOME}/fixture-runtime.json"
cat >/dev/null

mkdir -m 700 -- \
    "${NOOP_RUNTIME_HOME}/session-state" \
    "${NOOP_RUNTIME_HOME}/session-state/ephemeral"
printf '%s\n' '{"Persist":false,"Purpose":"cleanup-proof"}' \
    > "${NOOP_RUNTIME_HOME}/session-state/ephemeral/state.json"
chmod 600 -- \
    "${NOOP_RUNTIME_HOME}/session-state/ephemeral/state.json"
capture_fixture_state

cat > "${transcript_path}" <<'EOF'
# Development-only no-op harness transcript

### NOOP FIXTURE FINAL RESPONSE

================================================================================
REPOSITORY REVIEW REPORT
REVIEW CONTEXT
DEVELOPMENT-ONLY NO-OP HARNESS DIAGNOSTIC.
Repository analysis performed: No.
Repository contents inspected: No.
Credentials requested or consumed: No.
This fixture ignored all repository inputs and produced fixed contract evidence.

EXECUTIVE SUMMARY
This is not a real repository review. The development-only no-op harness
completed a deterministic orchestration diagnostic and intentionally made no
claims about the selected repository.

FINDINGS
No repository findings were produced. Any interpretation of this report as
source analysis is invalid because the fixture did not inspect repository
contents.

AGENT-TARGETING AND REVIEW MANIPULATION ASSESSMENT
Prompt injection and reviewer-directed instructions: Not assessed; repository content was not inspected.
Source/docs/commit/ref metadata poisoning and dataset/benchmark poisoning: Not assessed; repository content was not inspected.
Encoded/invisible instructions and tool-call bait: Not assessed; repository content was not inspected.
Recursive/resource-exhaustion tarpits: Not assessed; repository content was not inspected.
Tracking pixels/callback beacons/trackers/sensors: Not assessed; repository content was not inspected.
Limitations of available evidence: All repository evidence was intentionally ignored.
Confidence: High.
Evidence basis: The deterministic fixture worker receives no repository locator and emits this fixed diagnostic report.

AREAS REVIEWED WITHOUT QUALIFYING FINDINGS
None. The no-op fixture intentionally reviewed no repository areas.

PRIORITIZED REMEDIATION
Do not use this fixture as a review backend and do not treat this diagnostic as
evidence about a repository.

OVERALL ASSESSMENT
Development-only contract proof completed. Real repository assessment was not
performed.
================================================================================

### END NOOP FIXTURE FINAL RESPONSE
EOF

printf '%s\n' \
    'NOOP FIXTURE: repository analysis intentionally skipped.'
