name: Validate plugin

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Validate
        run: bash tests/validate-plugin.sh

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Validate
        shell: pwsh
        run: ./tests/validate-plugin.ps1
